config/routes.rb
Rails.application.routes.draw do

  root 'lending#index'
  
  resources :comments
  resources :posts
  devise_for :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    
    if user.nil?
      can :read, :all
    else
      can [:read, :create], :all
      can [:update, :destroy], Post, user_id: user.id
      can [:update, :destroy], Comment, user_id: user.id
    end
    
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user, :foreign_key => "user_id"
    belongs_to :post, :foreign_key => "post_id"
end

app/models/post.rb
class Post < ActiveRecord::Base
    # User authority apply to model
    resourcify
    
    has_many :comments, dependent: :destroy
    
    # Set up relation between models
    belongs_to :user, :foreign_key => "user_id"
    
    
    # Apply for image
    has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
    validates_attachment :image, :content_type => { :content_type => ["image/jpg", "image/png", "image/jpeg"] }
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  # Set up to relation between User Model and Post Model -> 1:N = User:Posts
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  # Applicate user's role
  rolify
  
  validates :email, :password, presence: true
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # CanCanCan Gem에서 발생하는 접근제어 예외 처리
  rescue_from CanCan::AccessDenied do |exception|
      respond_to do |format|
        format.json { head :forbidden, content_type: 'text/html' }
        format.html { redirect_to new_user_session_path, flash: {alert: exception.message} }
        format.js   { head :forbidden, content_type: 'text/html' }
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
     @comment_user = Comment.joins(:user)
  end

  # GET /comments/new
  # def new
  #   @comment = Comment.new
  # end

  # GET /comments/1/edit
  # def edit
  # end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment[:user_id] = current_user.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to URI(request.referer).path, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  # def update
  #   respond_to do |format|
  #     if @comment.update(comment_params)
  #       format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @comment }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @comment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to URI(request.referer).path, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment, :post_id)
    end
end

app/controllers/lending_controller.rb
class LendingController < ApplicationController
  skip_authorization_check
  
  def index
    # Inner Join between two models
    @posts = Post.joins(:user)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # 다른 액션이 실행되기 전에 실행되는 액션을 지정
  # only: 어떤 액션에만 적용될지 지정
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # CanCanCan에서 :read, :create, :update, :destory 액션에 대해 컨트롤러 액션과 매핑 해놓음
  # 사전에 매핑된 액션을 컨트롤러에 자동 적용
  # Aliase action - ability.rb에서 action_aliase로 수정 가능
  # - :index, :show, :to => :read
  # - :new, :to => :create
  # - :edit, :to => :update
  # - :destory => :destory
  load_and_authorize_resource

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @email = User.find(Post.find(params[:id])[:user_id])[:email]
    
    # Method is relative Comment model
    @comments = Comment.all
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post[:user_id] = current_user.id
    
    # begin
      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    # CanCanCan Gem에서 발생하는 접근제어 예외 처리
    # rescue CanCan::AccessDenied => exception
    #   respond_to do |format|
    #     format.json { head :forbidden, content_type: 'text/html' }
    #     format.html { redirect_to new_user_session_path, :alert => exception.message }
    #     format.js   { head :forbidden, content_type: 'text/html' }
    #   end
    # end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :desc, :content, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lending_helper.rb
module LendingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment, html: { class: "w3-row" }) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :post_id, value: params[:id] %>
  <%= f.label :comment %>
  <br>
  <div class="w3-padding">
    <span class="field w3-mobile">
      <%= f.text_area :comment, rows: 2, cols: 256, class: "w3-input w3-border w3-hover-shadow", style: "resize:none", placeholder: "댓글을 입력하세요." %>
    </span>
    <span class="actions w3-right w3-mobile">
      <%= f.submit '등록', class: "w3-button w3-theme" %>
      
    </span>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h6><strong>Comments</strong></h6>

<div class="container">
  <% @comments.each do |comment| %>
	<div class="timeline-item" date-is="<%= comment.created_at.strftime("%Y-%m-%d %a %p %I:%M:%S") %>">
		<p><strong><%= comment.user.email %></strong></p>
		<p>
			<%= comment.comment %>
		</p>
		<div class="w3-row">
		  <div class='w3-right'>
  		  <% if user_signed_in? && current_user.id == comment.user_id %>
          <%= link_to raw('<i Class="fa fa-close"></i> Delete'), comment,
                      method: :delete, data: { confirm: 'Are you sure?' }, class: "w3-btn w3-hover-opacity w3-round-xxlarge" %></td>
        <% end %>
      </div>
    </div>
	</div>
	<% end %>
</div>

app/views/comments/new.html.erb
<!-- <h3>New Comment</h3> -->

<%= render 'comments/form' %>

<!-- <%= link_to 'Back', comments_path %> -->

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SCH@Damgigo</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-teal.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="/css/timeline.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <style>
    @import url(https://fonts.googleapis.com/earlyaccess/nanumgothic.css);
    body,h1,h2,h3,h4,h5,h6 {
      font-family: "Nanum Gothic", "Raleway", sans-serif !important;
    }
    body, html {
        height: 100%;
        line-height: 1.8;
    }
    
    .w3-bar .w3-button {
        padding: 16px;
    }
    a {
      text-decoration:none !important;
    }
  </style>
</head>
<body>
<!-- Navbar (sit on top) -->
<div class="w3-top">
  <div class="w3-bar w3-theme w3-card-2" id="myNavbar">
    <a href="/" class="w3-bar-item w3-button w3-wide">SCH@Damgigo</a>
    <!-- Right-sided navbar links -->
    <div class="w3-right w3-hide-small">
      <%= link_to raw("<i class='fa fa-home'></i> HOME"), root_path, class: "w3-bar-item w3-button"  %>
      <%= link_to raw("<i class='fa fa-pencil'></i> NEW POST"), new_post_path, class: "w3-bar-item w3-button"  %>
      <% if user_signed_in? %>
        <%= link_to raw("<i class='fa fa-sign-out'></i> SIGN OUT"), destroy_user_session_path, method: 'delete', class: "w3-bar-item w3-button"  %>
      <% else %>
        <%= link_to raw("<i class='fa fa-user-o'></i> SIGN IN"), new_user_session_path, class: "w3-bar-item w3-button" %>
      <% end %>
    </div>
    <!-- Hide right-floated links on small screens and replace them with a menu icon -->
    <a href="javascript:void(0)" class="w3-bar-item w3-button w3-right w3-hide-large w3-hide-medium" onclick="w3_open()">
      <i class="fa fa-bars"></i>
    </a>
  </div>
</div>

<!-- Sidebar on small screens when clicking the menu icon -->
<nav class="w3-sidebar w3-bar-block w3-theme w3-card-2 w3-animate-left w3-hide-medium w3-hide-large" style="display:none" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-large w3-padding-16 w3-right">Close ×</a>
  <%= link_to raw("<i class='fa fa-home'></i> HOME"), root_path, class: "w3-bar-item w3-button"  %>
  <%= link_to raw("<i class='fa fa-pencil'></i> NEW POST"), new_post_path, class: "w3-bar-item w3-button"  %>
  <% if user_signed_in? %>
    <%= link_to raw("<i class='fa fa-sign-out'></i> SIGN OUT"), destroy_user_session_path, method: 'delete', class: "w3-bar-item w3-button"  %>
  <% else %>
    <%= link_to raw("<i class='fa fa-user-o'></i> SIGN IN"), new_user_session_path, class: "w3-bar-item w3-button" %>
  <% end %>
</nav>

<%= yield %>

<!-- Script for Sidebar, Tabs, Accordions, Progress bars and slideshows -->
<script>
  // Side navigation
  function w3_open() {
      var x = document.getElementById("mySidebar");
      x.style.width = "100%";
      x.style.fontSize = "40px";
      x.style.paddingTop = "10%";
      x.style.display = "block";
  }
  function w3_close() {
      document.getElementById("mySidebar").style.display = "none";
  }
  
  // Tabs
  function openCity(evt, cityName) {
    var i;
    var x = document.getElementsByClassName("city");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";
    }
    var activebtn = document.getElementsByClassName("testbtn");
    for (i = 0; i < x.length; i++) {
        activebtn[i].className = activebtn[i].className.replace(" w3-dark-grey", "");
    }
    document.getElementById(cityName).style.display = "block";
    evt.currentTarget.className += " w3-dark-grey";
  }
  
  var mybtn = document.getElementsByClassName("testbtn")[0];
  //mybtn.click();
  
  // Accordions
  function myAccFunc(id) {
      var x = document.getElementById(id);
      if (x.className.indexOf("w3-show") == -1) {
          x.className += " w3-show";
      } else { 
          x.className = x.className.replace(" w3-show", "");
      }
  }
  
  // Slideshows
  var slideIndex = 1;
  
  function plusDivs(n) {
  slideIndex = slideIndex + n;
  showDivs(slideIndex);
  }
  
  function showDivs(n) {
    var x = document.getElementsByClassName("mySlides");
    if (n > x.length) {slideIndex = 1}    
    if (n < 1) {slideIndex = x.length} ;
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
    x[slideIndex-1].style.display = "block";  
  }
  
  //showDivs(1);
  
  // Progress Bars
  function move() {
    var elem = document.getElementById("myBar");   
    var width = 5;
    var id = setInterval(frame, 10);
    function frame() {
      if (width == 100) {
        clearInterval(id);
      } else {
        width++; 
        elem.style.width = width + '%'; 
        elem.innerHTML = width * 1  + '%';
      }
    }
  }
</script>
</body>
</html>

app/views/lending/index.html.erb
<style>
  /* Full height image header */
    .bgimg-1 {
        background-position: center;
        background-size: cover;
        background-image: url("img/header.jpg");
        min-height: 30%;
    }
    
    body {
      background-color: #009688;
    }
</style>



<!-- Header with full-height image -->
<header class="bgimg-1 w3-display-container w3-grayscale-min" id="home">
  <div class="w3-display-top w3-center w3-text-white" style="padding:110px 45px 80px 45px">
    <span class="w3-jumbo w3-hide-small" style="text-shadow:3px 3px 0 #006e51"><strong>SCH@Damgigo</strong></span><br>
    <span class="w3-xxlarge w3-hide-large w3-hide-medium" style="text-shadow:2px 2px 0 #006e51"><strong>SCH@Damgigo</strong></span><br>
    <span class="w3-large" style="text-shadow:1px 1px 0 #006e51">학생들의 열정을 응원합니다. 학생 활동 크라우드 펀딩. 담기고.</span>
    <p><a href="#" class="w3-btn w3-theme-d1 w3-padding-large w3-large w3-margin-top w3-hover-opacity-off">Damgigo?</a></p>
  </div> 
</header>

<!-- Posts section -->
<div class="w3-container w3-theme" style="padding:30px 45px;" id="team">
  <h3 class="w3-left"><strong>프로젝트</strong></h3>
  <p class="w3-left w3-large w3-margin-left">학생들의 꿈에 기부하고 리워드를 받아보세요</p>
  <a href="/posts" class="w3-right w3-button">더보기 <i class="fa fa-angle-double-right"></i></a>
  
  <div class="w3-row-padding" style="margin-top:64px">
    <% @posts.each do |post| %>  
    <div class="w3-col l3 m6 w3-margin-bottom">
      <%= link_to post do %>
      <div class="w3-card-4 w3-hover-grayscale w3-white">
      <%= image_tag "#{post.image.url(:small)}", style: 'width:100%' %>
        <div class="w3-container">
          <h3><%= post.title %></h3>
          <p class="w3-opacity"><%= post.user.email %></p>
          <p><%= post.desc %></p>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
    
  </div>
</div>

app/views/posts/_form.html.erb
<div class="w3-card-4 w3-padding">
<%= form_for @post, html: { multipart: true, class: "w3-panel w3-margin-left w3-margin-right" } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>a
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, '프로젝트 제목' %><br>
    <%= f.text_field :title, class: "w3-input w3-hover-shadow", placeholder: "프로젝트 제목을 입력하세요.", autofocus: true, required: true %>
  </div>
  <div class="field">
    <%= f.label :desc, '프로젝트 설명' %><br>
    <%= f.text_field :desc, class: "w3-input w3-hover-shadow", placeholder: "프로젝트의 간단한 설명을 입력하세요.", required: true %>
  </div>
  <div class="field">
    <%= f.label :content, '프로젝트 내용' %><br>
    <%= f.text_area :content, class: "w3-input w3-hover-shadow", rows: 10, cols: 256, style: "resize:none", placeholder: "프로젝트의 내용을 입력하세요.", required: true %>
  </div>
  <div class="field">
    <%= f.label :image, '프로젝트 사진' %><br>
    <%= f.file_field :image, accept: 'image/png,image/gif,image/jpeg', id: "pictureInput", class: "w3-input w3-border-0", required: true%>
    <div class="w3-container">
      <div class="w3-row">
        <div class="w3-half">
          <% if @post.image? %>
            <label>기존 이미지</label>
            <div class="w3-padding-small">
              <%= image_tag @post.image.url(:original), class: "w3-image" %>
            </div>
          <% end %>
        </div>
        <div class="w3-half">
          <label>선택한 이미지</label>
          <div id="target" class="w3-padding-small"></div>
        </div>
      </div>
    </div>
    
  </div>
  
  <div class="actions">
    <%= f.submit '등록하기', class: "w3-button w3-right w3-theme w3-block" %>
  </div>
<% end %>

</div>

<script>
  $(function() {
    $('#pictureInput').on('change', function(event) {
      var files = event.target.files;
      var image = files[0]
      // here's the file size
      //console.log(image.size);
      var reader = new FileReader();
      
      reader.onload = function(file) {
        var img = new Image();
        //console.log(file);
        img.src = file.target.result;
        img.className = "w3-image";
        $('#target').html(img);
      }
      
      reader.readAsDataURL(image);
      //console.log(files);
    });
  });
</script>

app/views/posts/edit.html.erb
<!-- Posts section -->

<div class="w3-container" style="padding:30px 45px; margin-top: 40px;" id="team">
  <div class="w3-row">
    <div class="w3-content">
      <h1 class="w3-padding-large w3-left"><strong>프로젝트 수정</strong></h1>
      <div class="w3-right w3-padding-large">
      <%= link_to raw('<i class="fa fa-arrow-circle-left"></i> Back'), URI(request.referer).path, class: "w3-btn w3-hover-opacity w3-round-xxlarge" %>
      </div>
      <div class="w3-container w3-margin-top">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<!-- Posts section -->
<div class="w3-container" style="padding:30px 45px; margin-top: 40px;">
  <div class="w3-row">
    <h3 class="w3-left">프로젝트</h3>
    <p class="w3-left w3-large w3-margin-left">- 다양한 프로젝트를 살펴보세요</p>
    <div class="w3-right w3-padding-large">
      <%= link_to raw('<i class="fa fa-arrow-circle-left"></i> Back'), posts_path, class: "w3-btn w3-hover-opacity w3-round-xxlarge", onclick: "javascript:history.back();" %>
    </div>
    <div class="w3-row-padding" style="margin-top:64px">
      <% @posts.each do |post| %>  
      <div class="w3-col l3 m6 w3-margin-bottom">
        <%= link_to post do %>
        <div class="w3-card-2">
        <%= image_tag "#{post.image.url(:small)}", style: 'width:100%' %>
          <div class="w3-container">
            <h3><%= post.title %></h3>
            <p class="w3-opacity"><%= post.user.email %></p>
            <p><%= post.desc %></p>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<!-- Posts section -->

<div class="w3-container" style="padding:30px 45px; margin-top: 40px;" id="team">
  <div class="w3-row">
    <div class="w3-content">
      <h1 class="w3-padding-large w3-left"><strong>새 프로젝트 등록</strong></h1>
      <div class="w3-right w3-padding-large">
      <%= link_to raw('<i class="fa fa-arrow-circle-left"></i> Back'), URI(request.referer).path, class: "w3-btn w3-hover-opacity w3-round-xxlarge" %>
        
      </div>
      <div class="w3-container w3-margin-top">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<!-- Posts section -->

<div class="w3-container" style="padding:30px 45px; margin-top: 40px;">
  <div class="w3-row">
    <div class="w3-content w3-card-4">
      <div class="w3-panel">
        <h1 class="w3-padding w3-left"><strong><%= @post.title %></strong></h1>
        <p class="w3-padding w3-large w3-left w3-opacity"><%= @email %></p>
        <div class="w3-right w3-padding-large">
          <% if user_signed_in? && current_user.id == @post.user_id %>
            <%= link_to raw('<i Class="fa fa-pencil-square-o"></i> Edit'), edit_post_path(@post), class: "w3-btn w3-hover-opacity w3-round-xxlarge" %>
            <%= link_to raw('<i Class="fa fa-close"></i> Delete'), post_path(@post),
                        method: :delete, data: { confirm: 'Are you sure?' }, class: "w3-btn w3-hover-opacity w3-round-xxlarge" %></td>
          <% end %>
          <%= link_to raw('<i class="fa fa-arrow-circle-left"></i> Back'), URI(request.referer).path, class: "w3-btn w3-hover-opacity w3-round-xxlarge" %>
        </div>
      </div>
      <div class="w3-container">
        <div class="w3-row">
          <p><%= @post.desc %></p>
          <p><%= link_to image_tag(@post.image.url(:original), class: "w3-image"), @post.image.url %></p>
          <hr>  
          <p><strong>Content:</strong><%= @post.content %></p>
        </div>
        <hr class="w3-border" />
        
        <div class="w3-row">
          <div class="w3-panel ">
          <%= render 'comments/form' %>
          </div>
        </div>
        <hr>
        <div class="w3-row">
          <div class="w3-content w3-padding-large">
            <%= render :template => 'comments/index' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>